# Generated by Django 6.0.8 on 2026-09-02 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_blog', '0064_recent_events_block__see_all_events_link'),
        ('sites_conformes_blog', '0065_alter_blogentrypage_body_and_more'),
    ]

    operations = [
    ]
