# Generated by Django 6.0.8 on 2026-09-02 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites_conformes_events', '0036_recent_events_block__see_all_events_link'),
        ('sites_conformes_events', '0037_alter_evententrypage_body_and_more'),
    ]

    operations = [
    ]
